tarefa1 : 
	@echo "Este comando não é o correto!"

tarefa2 : 
	@openssl enc -aes-128-ctr -K 123454321 -in justiceleague.enc -iv 0 2> /dev/null

tarefa3 : 
	@openssl enc -aes-128-ctr -K 123456789 -in justiceleague.enc -iv 0 2> /dev/null

tarefa4 : 
	@openssl enc -aes-128-ctr -K 987656789 -in justiceleague.enc -iv 0 2> /dev/null

tarefa5 : 
	@openssl enc -aes-128-ctr -K 987654321 -in justiceleague.enc -iv 0 2> /dev/null

